name: play_game_service
description: A Google Play Games Service Plugin, Created for my little game app. Only support Android for now, but nullsafe
version: 0.2.3
homepage: https://github.com/gujianming/play_game_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.iyond.minigame.play_game_service
        pluginClass: PlayGameServicePlugin
